[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_VERSION = "10.7.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[visual]
  enable = true
  framework = "react"
  ssg = "vite"
